[package]
name = "query_embedding"
version = "0.1.0"
edition = "2024"

[dependencies]
gf-embed = { path = "../gf-embed" }
embed_anything.workspace = true
protobuf.workspace = true
clap.workspace = true
walkdir.workspace = true
tokio = "1.45.0"
candle-core = "0.9.1"
