[package]
name = "make_embedding"
version = "0.1.0"
edition = "2024"

[dependencies]
protobuf.workspace = true
home.workspace = true
gf-metadata = { path = "../gf-metadata" }
embed_anything = "0.5.5"
clap.workspace = true
walkdir.workspace = true
regex.workspace = true
itertools = "0.14.0"
